(() => {
'use strict';
const app=document.querySelector('#app'),modal=document.querySelector('#modal'),stages=window.STAGES,KEY='pium-petals-v1';
const fresh=()=>({version:1,started:false,completed:[],current:0,seen:[[],[],[],[],[]],sound:false});
let state=fresh(),storageOK=true,view='title',stageIndex=0,question=0,answered=false,busy=false,audio;
try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved&&saved.version===1){let count=0;while(count<5&&Array.isArray(saved.completed)&&saved.completed.includes(count))count++;state={...fresh(),started:!!saved.started,completed:Array.from({length:count},(_,i)=>i),current:Math.min(Math.max(Number.isInteger(saved.current)?saved.current:0,0),Math.min(count,4)),sound:!!saved.sound,seen:Array.from({length:5},(_,i)=>Array.isArray(saved.seen?.[i])?[...new Set(saved.seen[i].filter(n=>Number.isInteger(n)&&n>=0&&n<3))]:[])};}}catch{storageOK=false;}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true;}catch{storageOK=false;}}
const count=()=>state.completed.length;
function mascot(n=count(),cls='',animate=false){if(n===5&&!animate)return `<div class="mascot ${cls}" role="img" aria-label="꽃잎 회복 5/5 상태의 피움이"><img src="assets/pium-original.png" alt="" draggable="false"></div>`;return `<div class="mascot ${cls}" role="img" aria-label="꽃잎 회복 ${n}/5 상태의 피움이"><img src="assets/pium-base.png" alt="" draggable="false">${Array.from({length:n},(_,i)=>`<img class="${animate&&i===n-1?'petal':''}" src="assets/petal-${i+1}.png" alt="" draggable="false">`).join('')}</div>`;}
function sound(win=false){if(!state.sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();[0,...(win?[.13,.26]:[])].forEach((delay,i)=>{const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.type='sine';o.frequency.value=[523,659,784][i];const t=audio.currentTime+delay;g.gain.setValueAtTime(.055,t);g.gain.exponentialRampToValueAtTime(.001,t+.18);o.start(t);o.stop(t+.2);});}catch{}}
function top(){window.scrollTo({top:0,behavior:'instant'});}
function title(){view='title';app.innerHTML=`<section class="title-screen"><div class="title-art"></div><div class="title-layout"><div class="title-copy"><span class="eyebrow">동신대학교 학생상담센터</span><h1>피움이의<br><span>꽃잎 되찾기</span></h1><p>마음을 알아가는 작은 모험,<br>우리 함께 다시 피어나 볼까?</p><button class="primary" id="start">${state.started?'모험 이어하기':'모험 시작'}</button><div class="title-meta">다섯 장소 · 약 5~10분<br>${state.started?`꽃잎 회복 ${count()}/5 · 지난 모험을 기억하고 있어`:'터치로 탐험하고, 언제든 이어서 플레이'}</div></div><div class="title-character"><div class="bubble">${state.started?'다시 만나서 반가워!<br>우리의 모험을 이어가 볼까?':'내 꽃잎이 사라졌어…<br>나랑 함께 꽃잎을 되찾으러 가줄래?'}</div>${mascot(count(),'float')}</div></div><div class="title-footer">피움이와 함께하는 마음 탐험</div></section>`;document.querySelector('#start').onclick=()=>{state.started=true;save();sound();map();};top();}
function shell(body,message){app.innerHTML=`<div class="game-shell"><aside class="sidebar panel"><h1 class="brand">피움이의<br>꽃잎 되찾기</h1>${mascot()}<div class="progress-row"><b>꽃잎 회복 ${count()}/5</b><span>${count()===5?'모험 완성':'마음 탐험 중'}</span></div><div class="dots" aria-hidden="true">${Array.from({length:5},(_,i)=>`<span class="${i<count()?'on':''}"></span>`).join('')}</div><div class="dialogue"><strong>피움이</strong><p>${message}</p></div><div class="toolbar"><button class="secondary" id="map-button">모험 지도</button><button class="secondary" id="guide-button">이용 안내</button><button class="secondary" id="sound-button" aria-pressed="${state.sound}">소리 ${state.sound?'켜짐':'꺼짐'}</button></div>${!storageOK?'<div class="save-warning">이 브라우저에서 저장할 수 없어. 창을 닫으면 진행이 사라질 수 있어.</div>':''}</aside><section id="surface">${body}</section></div>`;
document.querySelector('#map-button').onclick=()=>{if(!busy)map();};document.querySelector('#guide-button').onclick=showGuide;document.querySelector('#sound-button').onclick=e=>{state.sound=!state.sound;save();e.currentTarget.textContent=`소리 ${state.sound?'켜짐':'꺼짐'}`;e.currentTarget.setAttribute('aria-pressed',state.sound);sound();};}
function map(){if(busy)return;view='map';const current=state.current;const body=`<div class="panel map-panel"><header class="map-head"><h2>마음의 정원</h2><span>현재 · ${stages[current].name}</span></header><div class="world" aria-label="길로 연결된 다섯 장소의 모험 지도">${stages.map((s,i)=>{const done=state.completed.includes(i),locked=i>count();return `<button class="map-node ${locked?'locked':done?'done':'next'}" data-place="${i}" style="left:${s.pos[0]}%;top:${s.pos[1]}%" ${locked?'disabled':''} aria-label="${i+1}. ${s.name} · ${locked?'아직 잠김':done?'완료, 다시 방문':'다음 탐험'}"><span class="node-circle" aria-hidden="true">${locked?'🔒':done?'✓':i+1}</span><span class="node-name">${s.name}</span><span class="node-state">${locked?'이전 장소 완료 후':done?'완료 · 다시 보기':'다음 탐험'}</span></button>`;}).join('')}<div class="walker" style="left:${stages[current].pos[0]-13}%;top:${stages[current].pos[1]+2}%">${mascot()}</div></div></div><p class="map-note">밝게 빛나는 장소를 터치해 봐. 완료한 장소도 다시 갈 수 있어.</p>${count()===5?'<p style="text-align:center"><button class="primary" id="ending-button">활짝 핀 피움이 만나기</button></p>':''}<p style="text-align:center"><button class="reset-link" id="reset-button">처음부터 다시 하기</button></p>`;
shell(body,count()===5?'다섯 장소를 모두 탐험했어! 마음이 쉬고 싶을 때, 센터를 기억해 줘.':`${stages[Math.min(count(),4)].name}에 꽃잎의 단서가 있어. 길을 따라 함께 가보자!`);
document.querySelectorAll('[data-place]').forEach(b=>b.onclick=()=>travel(Number(b.dataset.place)));document.querySelector('#reset-button').onclick=resetConfirm;document.querySelector('#ending-button')?.addEventListener('click',ending);top();}
async function travel(i){if(!Number.isInteger(i)||i<0||i>=5||i>count())throw new Error('아직 갈 수 없는 장소예요. 이전 장소를 먼저 완료해 주세요.');if(busy)return;busy=true;sound();const walker=document.querySelector('.walker');if(walker){document.querySelectorAll('[data-place]').forEach(b=>b.disabled=true);const from=state.current,to=i,frames=[{left:`${stages[from].pos[0]-13}%`,top:`${stages[from].pos[1]+2}%`}];const step=to>=from?1:-1;for(let n=from;n!==to;n+=step){const a=stages[n].pos,b=stages[n+step].pos;frames.push({left:`${(a[0]+b[0])/2}%`,top:`${(a[1]+b[1])/2+2}%`},{left:`${b[0]-13}%`,top:`${b[1]+2}%`});}walker.classList.add('walking');const duration=matchMedia('(prefers-reduced-motion: reduce)').matches?0:Math.max(400,Math.abs(to-from)*800);await walker.animate(frames,{duration,fill:'forwards',easing:'ease-in-out'}).finished.catch(()=>{});}
state.current=i;save();busy=false;enter(i);}
function enter(i){if(i>count()||i<0||i>=5)return;stageIndex=i;view='stage';question=0;answered=false;renderStage(false);top();}
function header(s){return `<header class="stage-head"><div class="eyebrow">CHAPTER ${String(stageIndex+1).padStart(2,'0')} / 05</div><h2>${s.name}</h2><p>${s.subtitle}</p></header>`;}
function renderStage(exploring){const s=stages[stageIndex],done=state.completed.includes(stageIndex);shell(`<article class="panel stage">${header(s)}<div class="stage-body">${done?'<div class="visit-badge">✓ 이미 회복한 꽃잎이야 · 편하게 다시 둘러봐</div>':''}<div class="stage-intro">${mascot()}<div class="bubble">${s.intro}</div></div>${exploring?exploreHTML(s):'<div class="stage-actions"><button class="primary" id="explore-button">단서 찾아보기</button></div>'}</div></article>`,`현재 · ${s.name}<br>${exploring?'세 가지 오브젝트를 터치해서 꽃잎의 단서를 모아 줘.':'짧은 이야기 뒤에 탐험이 시작돼!'}`);
if(exploring)bindExplore();else document.querySelector('#explore-button').onclick=()=>{sound();renderStage(true);};}
function exploreHTML(s){const seen=state.seen[stageIndex];return `<div class="objects">${s.objects.map((o,j)=>`<button class="object ${seen.includes(j)?'read':''}" data-object="${j}" aria-label="${o.name}${seen.includes(j)?', 확인함':''}"><span class="object-icon" aria-hidden="true">${o.icon}</span>${o.name}<em>${seen.includes(j)?'✓ 발견한 단서':'터치해서 살펴보기'}</em></button>`).join('')}</div><section class="reading" id="reading" aria-live="polite"><h3>여기에는 어떤 이야기가 있을까?</h3><p>위의 세 가지 오브젝트를 하나씩 터치해 봐.</p></section><div class="mission"><span class="badge" id="clue-count">찾은 단서 ${seen.length}/3</span><p class="small" style="margin-top:12px">단서를 모두 찾으면 두 가지 미션에 도전할 수 있어.</p><button class="primary" id="mission-button" ${seen.length<3?'disabled':''}>${state.completed.includes(stageIndex)?'미션 다시 풀기':'꽃잎 미션 도전'}</button></div>${stageIndex===4?window.EXTRA_INFO:''}`;}
function bindExplore(){document.querySelectorAll('[data-object]').forEach(b=>b.onclick=()=>{const j=Number(b.dataset.object),s=stages[stageIndex],o=s.objects[j];if(!state.seen[stageIndex].includes(j)){state.seen[stageIndex].push(j);save();}b.classList.add('read');b.querySelector('em').textContent='✓ 발견한 단서';b.setAttribute('aria-label',`${o.name}, 확인함`);document.querySelector('#reading').innerHTML=`<h3>${o.title}</h3>${o.text.map(t=>`<p>${t}</p>`).join('')}<p class="source">${s.source} 바탕</p>`;document.querySelector('#clue-count').textContent=`찾은 단서 ${state.seen[stageIndex].length}/3`;document.querySelector('#mission-button').disabled=state.seen[stageIndex].length<3;sound();});document.querySelector('#mission-button').onclick=()=>{if(state.seen[stageIndex].length!==3)return;question=0;answered=false;renderQuiz();top();};}
function renderQuiz(){const s=stages[stageIndex],q=s.questions[question];view='quiz';shell(`<article class="panel stage">${header(s)}<div class="stage-body"><div class="stage-intro">${mascot()}<div class="bubble">모아온 단서로 함께 풀어보자.<br>틀려도 괜찮아. 내가 힌트를 줄게!</div></div><section class="mission"><span class="eyebrow">꽃잎 미션 ${question+1} / ${s.questions.length}</span><p class="question">${q.q}</p><div class="answers">${q.options.map((x,j)=>`<button class="answer" data-answer="${j}">${x}</button>`).join('')}</div><div class="feedback" id="feedback" role="status" aria-live="polite"></div><div class="stage-actions"><button class="secondary" id="review-clues">단서 다시 보기</button><button class="primary hidden" id="next-question">${question===s.questions.length-1?'꽃잎 만나기':'다음 미션'}</button></div></section></div></article>`,'천천히 생각해도 괜찮아. 점수나 시간제한은 없어.');
document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{if(answered)return;const choice=Number(b.dataset.answer);const feedback=document.querySelector('#feedback');document.querySelectorAll('.answer').forEach(el=>el.classList.remove('wrong'));if(choice!==q.answer){b.classList.add('wrong');feedback.className='feedback';feedback.innerHTML=`<strong>피움이의 힌트</strong><br>괜찮아, 다시 해보자! ${q.hint}`;return;}answered=true;b.classList.add('correct');document.querySelectorAll('.answer').forEach(el=>el.disabled=true);feedback.className='feedback success';feedback.innerHTML=`<strong>피움이</strong><br>${q.why}`;document.querySelector('#next-question').classList.remove('hidden');sound(true);});
document.querySelector('#review-clues').onclick=()=>renderStage(true);document.querySelector('#next-question').onclick=()=>{if(!answered)return;if(question<s.questions.length-1){question++;answered=false;renderQuiz();top();}else finish();};}
function finish(){if(view!=='quiz'||!answered||question!==stages[stageIndex].questions.length-1)return;const isNew=!state.completed.includes(stageIndex);if(isNew&&stageIndex!==count())return;if(isNew){state.completed.push(stageIndex);save();}view='reward';const n=count();shell(`<article class="panel reward"><span class="eyebrow">${isNew?'PETAL RECOVERED':'다시 만난 마음의 단서'}</span><h2>${isNew?'꽃잎이 다시 피어났어!':'잘 기억하고 있구나!'}</h2>${mascot(n,'',isNew)}${Array.from({length:8},(_,j)=>`<span class="sparkle" style="left:${12+(j*23)%77}%;top:${18+(j*17)%35}%;animation-delay:${j*.17}s">✧</span>`).join('')}<p>${isNew?'와! 꽃잎이 다시 자랐어!<br>다음 장소도 함께 가보자!':'이 장소의 꽃잎은 이미 회복했어.<br>다시 찾아줘서 고마워!'}</p><span class="badge">꽃잎 회복 ${n}/5</span><div class="stage-actions"><button class="primary" id="reward-next">${n===5?'활짝 핀 피움이 만나기':'모험 지도로 돌아가기'}</button></div></article>`,isNew?'네가 찾은 마음의 단서 덕분이야!':'완료한 장소를 다시 방문해도 꽃잎은 한 번만 회복돼.');document.querySelector('#reward-next').onclick=()=>n===5?ending():map();sound(true);top();}
function guideHTML(){return `<div class="guide"><h3>마음이 쉬고 싶을 때, 기억해 줘</h3><p><b>찾아가는 곳</b><br>동신행정관 1층 105호 · 동신대학교 학생상담센터</p><p><b>개인상담 · 심리검사 신청</b><br>센터 홈페이지, 자료의 QR, 전화 또는 방문<br>개인상담은 QR 인식 후 네이버폼 신청으로 안내돼 있어.</p><a href="tel:0613304035">☎ 061-330-4035</a><p><b>개인상담 이용 순서</b><br>상담신청 → 접수상담 → 상담자 배정 → 상담진행<br>자료 안내: 주 1회 50분</p><details><summary>프로그램별 신청 · 자료 속 혜택</summary><p>미술치료 집단상담: QR 인식 후 상상시스템 신청. 3회 이상 참여 시 마일리지 3,000점.<br>학업 동기강화: 상상시스템 또는 061-330-4037로 신청. 집단상담 후 학업 멘토링 참여 시 마일리지 5,000점.<br>개인상담: 5회기 이상 시 마일리지 2,000점.<br>심리검사: 해석상담까지 진행 시 마일리지 2,000점.</p><p>자료의 개인상담 신청기간은 2026. 3. 3.~12. 31., 심리검사는 2026. 3. 3.~2027. 1. 30.이야. 일정·모집 여부·혜택은 프로그램별 센터 안내를 확인해 줘.</p></details><details><summary>자료 마지막의 문의처</summary><a href="tel:0613304037">☎ 061-330-4037</a><br><a href="mailto:gnb4787@dsu.ac.kr">gnb4787@dsu.ac.kr</a></details><p class="source-notice">첨부 소개 자료 3·6·7·16쪽 기준. 운영시간은 자료에 기재되어 있지 않아. 이 게임은 상담 신청을 직접 접수하지 않아.</p></div>`;}
function ending(){if(count()!==5)return;view='ending';shell(`<article class="panel ending">${Array.from({length:22},(_,j)=>`<i class="confetti" style="left:${(j*47)%100}%;animation-delay:${-j*.37}s;animation-duration:${5+j%4}s;background:${['#fffef0','#fee29b','#b9e794'][j%3]}"></i>`).join('')}<span class="eyebrow">OUR GARDEN IS IN BLOOM</span><h2>마음도, 꽃잎도 활짝!</h2>${mascot(5)}<p><b>덕분에 내 꽃잎이 모두 피어났어!<br>너의 마음도 활짝 피어나길 바라!</b></p><span class="badge">다섯 장소 탐험 완료 · 꽃잎 회복 5/5</span>${guideHTML()}<div class="stage-actions"><button class="primary" id="back-map">지도 돌아가기</button><button class="secondary" id="restart">처음부터 다시 하기</button></div></article>`,'우리의 모험은 끝났지만, 학생상담센터는 기억해 줘. 언제든 안내를 다시 읽을 수 있어.');document.querySelector('#back-map').onclick=map;document.querySelector('#restart').onclick=resetConfirm;top();}
function showGuide(){modal.innerHTML=`<h2>학생상담센터 이용 안내</h2>${guideHTML()}${window.EXTRA_INFO}<div class="buttons"><button class="primary" id="close-modal">모험으로 돌아가기</button></div>`;modal.showModal();document.querySelector('#close-modal').onclick=()=>modal.close();}
function resetConfirm(){modal.innerHTML='<h2>처음부터 다시 시작할까?</h2><p>이 브라우저에 저장된 완료 장소와 꽃잎 회복 기록이 모두 초기화돼.</p><div class="buttons"><button class="secondary" id="cancel-reset">취소하고 계속하기</button><button class="primary" id="confirm-reset">초기화하고 시작하기</button></div>';modal.showModal();document.querySelector('#cancel-reset').onclick=()=>modal.close();document.querySelector('#confirm-reset').onclick=()=>{state=fresh();save();modal.close();title();};}
// Browser-native agent access follows the same navigation guard as touch controls.
const context=document.modelContext;if(context?.registerTool){const lifecycle=new AbortController();for(const tool of [{name:'read_pium_progress',title:'피움이 모험 진행 확인',description:'현재 완료 장소와 회복 단계를 읽습니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({recovery:count(),completed:state.completed.map(i=>stages[i].name),current:stages[state.current].name,view})},{name:'open_pium_place',title:'열린 장소 방문',description:'1~5번 중 잠금이 해제된 장소를 방문합니다. 미션 완료나 꽃잎 회복을 대신하지 않습니다.',inputSchema:{type:'object',properties:{place:{type:'integer',minimum:1,maximum:5}},required:['place'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async input=>{if(!Number.isInteger(input?.place)||input.place<1||input.place>5||input.place-1>count())throw new Error('유효한 열린 장소 번호가 필요합니다.');state.started=true;save();await travel(input.place-1);return {place:stages[input.place-1].name,recovery:count()};}}]){try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
title();
})();
